/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as InvolveRouteImport } from './routes/involve'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as AdvocacyRouteImport } from './routes/advocacy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruthStoryIdRouteImport } from './routes/truth_.$storyId'
import { Route as ResourcesGuideIdRouteImport } from './routes/resources_.$guideId'
import { Route as ApplyVolunteerRouteImport } from './routes/apply.volunteer'
import { Route as ApplyPartnerRouteImport } from './routes/apply.partner'
import { Route as ApplyAmbassadorRouteImport } from './routes/apply.ambassador'
import { Route as ApiSubmitRouteImport } from './routes/api/submit'
import { Route as ApiAdminSubmissionsRouteImport } from './routes/api/admin/submissions'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const InvolveRoute = InvolveRouteImport.update({
  id: '/involve',
  path: '/involve',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocacyRoute = AdvocacyRouteImport.update({
  id: '/advocacy',
  path: '/advocacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthStoryIdRoute = TruthStoryIdRouteImport.update({
  id: '/truth_/$storyId',
  path: '/truth/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesGuideIdRoute = ResourcesGuideIdRouteImport.update({
  id: '/resources_/$guideId',
  path: '/resources/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyVolunteerRoute = ApplyVolunteerRouteImport.update({
  id: '/apply/volunteer',
  path: '/apply/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyPartnerRoute = ApplyPartnerRouteImport.update({
  id: '/apply/partner',
  path: '/apply/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAmbassadorRoute = ApplyAmbassadorRouteImport.update({
  id: '/apply/ambassador',
  path: '/apply/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitRoute = ApiSubmitRouteImport.update({
  id: '/api/submit',
  path: '/api/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsRoute = ApiAdminSubmissionsRouteImport.update({
  id: '/api/admin/submissions',
  path: '/api/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advocacy': typeof AdvocacyRoute
  '/circle': typeof CircleRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/involve': typeof InvolveRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/truth': typeof TruthRoute
  '/work': typeof WorkRoute
  '/api/submit': typeof ApiSubmitRoute
  '/apply/ambassador': typeof ApplyAmbassadorRoute
  '/apply/partner': typeof ApplyPartnerRoute
  '/apply/volunteer': typeof ApplyVolunteerRoute
  '/resources/$guideId': typeof ResourcesGuideIdRoute
  '/truth/$storyId': typeof TruthStoryIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advocacy': typeof AdvocacyRoute
  '/circle': typeof CircleRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/involve': typeof InvolveRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/truth': typeof TruthRoute
  '/work': typeof WorkRoute
  '/api/submit': typeof ApiSubmitRoute
  '/apply/ambassador': typeof ApplyAmbassadorRoute
  '/apply/partner': typeof ApplyPartnerRoute
  '/apply/volunteer': typeof ApplyVolunteerRoute
  '/resources/$guideId': typeof ResourcesGuideIdRoute
  '/truth/$storyId': typeof TruthStoryIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advocacy': typeof AdvocacyRoute
  '/circle': typeof CircleRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/involve': typeof InvolveRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/truth': typeof TruthRoute
  '/work': typeof WorkRoute
  '/api/submit': typeof ApiSubmitRoute
  '/apply/ambassador': typeof ApplyAmbassadorRoute
  '/apply/partner': typeof ApplyPartnerRoute
  '/apply/volunteer': typeof ApplyVolunteerRoute
  '/resources_/$guideId': typeof ResourcesGuideIdRoute
  '/truth_/$storyId': typeof TruthStoryIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advocacy'
    | '/circle'
    | '/contact'
    | '/games'
    | '/involve'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/truth'
    | '/work'
    | '/api/submit'
    | '/apply/ambassador'
    | '/apply/partner'
    | '/apply/volunteer'
    | '/resources/$guideId'
    | '/truth/$storyId'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advocacy'
    | '/circle'
    | '/contact'
    | '/games'
    | '/involve'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/truth'
    | '/work'
    | '/api/submit'
    | '/apply/ambassador'
    | '/apply/partner'
    | '/apply/volunteer'
    | '/resources/$guideId'
    | '/truth/$storyId'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/submissions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advocacy'
    | '/circle'
    | '/contact'
    | '/games'
    | '/involve'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/truth'
    | '/work'
    | '/api/submit'
    | '/apply/ambassador'
    | '/apply/partner'
    | '/apply/volunteer'
    | '/resources_/$guideId'
    | '/truth_/$storyId'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdvocacyRoute: typeof AdvocacyRoute
  CircleRoute: typeof CircleRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRoute
  InvolveRoute: typeof InvolveRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TruthRoute: typeof TruthRoute
  WorkRoute: typeof WorkRoute
  ApiSubmitRoute: typeof ApiSubmitRoute
  ApplyAmbassadorRoute: typeof ApplyAmbassadorRoute
  ApplyPartnerRoute: typeof ApplyPartnerRoute
  ApplyVolunteerRoute: typeof ApplyVolunteerRoute
  ResourcesGuideIdRoute: typeof ResourcesGuideIdRoute
  TruthStoryIdRoute: typeof TruthStoryIdRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminSubmissionsRoute: typeof ApiAdminSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/involve': {
      id: '/involve'
      path: '/involve'
      fullPath: '/involve'
      preLoaderRoute: typeof InvolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocacy': {
      id: '/advocacy'
      path: '/advocacy'
      fullPath: '/advocacy'
      preLoaderRoute: typeof AdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth_/$storyId': {
      id: '/truth_/$storyId'
      path: '/truth/$storyId'
      fullPath: '/truth/$storyId'
      preLoaderRoute: typeof TruthStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources_/$guideId': {
      id: '/resources_/$guideId'
      path: '/resources/$guideId'
      fullPath: '/resources/$guideId'
      preLoaderRoute: typeof ResourcesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/volunteer': {
      id: '/apply/volunteer'
      path: '/apply/volunteer'
      fullPath: '/apply/volunteer'
      preLoaderRoute: typeof ApplyVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/partner': {
      id: '/apply/partner'
      path: '/apply/partner'
      fullPath: '/apply/partner'
      preLoaderRoute: typeof ApplyPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/ambassador': {
      id: '/apply/ambassador'
      path: '/apply/ambassador'
      fullPath: '/apply/ambassador'
      preLoaderRoute: typeof ApplyAmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit': {
      id: '/api/submit'
      path: '/api/submit'
      fullPath: '/api/submit'
      preLoaderRoute: typeof ApiSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions': {
      id: '/api/admin/submissions'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions'
      preLoaderRoute: typeof ApiAdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdvocacyRoute: AdvocacyRoute,
  CircleRoute: CircleRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRoute,
  InvolveRoute: InvolveRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TruthRoute: TruthRoute,
  WorkRoute: WorkRoute,
  ApiSubmitRoute: ApiSubmitRoute,
  ApplyAmbassadorRoute: ApplyAmbassadorRoute,
  ApplyPartnerRoute: ApplyPartnerRoute,
  ApplyVolunteerRoute: ApplyVolunteerRoute,
  ResourcesGuideIdRoute: ResourcesGuideIdRoute,
  TruthStoryIdRoute: TruthStoryIdRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminSubmissionsRoute: ApiAdminSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
